// THIS CODE WAS AUTOMATICALLY GENERATED
// DO NOT EDIT THIS CODE BY HAND
// YOU CAN REGENERATE IT USING yarn generate:lib

import { es2015_symbol } from './es2015.symbol';

export const es2015_iterable = {
  ...es2015_symbol,
  SymbolConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'SymbolConstructor',
    writeable: false,
  },
  IteratorYieldResult: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'IteratorYieldResult',
    writeable: false,
  },
  IteratorReturnResult: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'IteratorReturnResult',
    writeable: false,
  },
  IteratorResult: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'IteratorResult',
    writeable: false,
  },
  Iterator: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Iterator',
    writeable: false,
  },
  Iterable: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Iterable',
    writeable: false,
  },
  IterableIterator: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'IterableIterator',
    writeable: false,
  },
  Array: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Array',
    writeable: false,
  },
  ArrayConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ArrayConstructor',
    writeable: false,
  },
  ReadonlyArray: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ReadonlyArray',
    writeable: false,
  },
  IArguments: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'IArguments',
    writeable: false,
  },
  Map: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Map',
    writeable: false,
  },
  ReadonlyMap: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ReadonlyMap',
    writeable: false,
  },
  MapConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'MapConstructor',
    writeable: false,
  },
  WeakMap: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WeakMap',
    writeable: false,
  },
  WeakMapConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WeakMapConstructor',
    writeable: false,
  },
  Set: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Set',
    writeable: false,
  },
  ReadonlySet: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ReadonlySet',
    writeable: false,
  },
  SetConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'SetConstructor',
    writeable: false,
  },
  WeakSet: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WeakSet',
    writeable: false,
  },
  WeakSetConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WeakSetConstructor',
    writeable: false,
  },
  Promise: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Promise',
    writeable: false,
  },
  PromiseConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PromiseConstructor',
    writeable: false,
  },
  Reflect: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Reflect',
    writeable: false,
  },
  String: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'String',
    writeable: false,
  },
  Int8Array: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Int8Array',
    writeable: false,
  },
  Int8ArrayConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Int8ArrayConstructor',
    writeable: false,
  },
  Uint8Array: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Uint8Array',
    writeable: false,
  },
  Uint8ArrayConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Uint8ArrayConstructor',
    writeable: false,
  },
  Uint8ClampedArray: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Uint8ClampedArray',
    writeable: false,
  },
  Uint8ClampedArrayConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Uint8ClampedArrayConstructor',
    writeable: false,
  },
  Int16Array: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Int16Array',
    writeable: false,
  },
  Int16ArrayConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Int16ArrayConstructor',
    writeable: false,
  },
  Uint16Array: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Uint16Array',
    writeable: false,
  },
  Uint16ArrayConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Uint16ArrayConstructor',
    writeable: false,
  },
  Int32Array: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Int32Array',
    writeable: false,
  },
  Int32ArrayConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Int32ArrayConstructor',
    writeable: false,
  },
  Uint32Array: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Uint32Array',
    writeable: false,
  },
  Uint32ArrayConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Uint32ArrayConstructor',
    writeable: false,
  },
  Float32Array: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Float32Array',
    writeable: false,
  },
  Float32ArrayConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Float32ArrayConstructor',
    writeable: false,
  },
  Float64Array: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Float64Array',
    writeable: false,
  },
  Float64ArrayConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Float64ArrayConstructor',
    writeable: false,
  },
};
