// THIS CODE WAS AUTOMATICALLY GENERATED
// DO NOT EDIT THIS CODE BY HAND
// YOU CAN REGENERATE IT USING yarn generate:lib

export const es5 = {
  Symbol: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Symbol',
    writeable: false,
  },
  PropertyKey: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PropertyKey',
    writeable: false,
  },
  PropertyDescriptor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PropertyDescriptor',
    writeable: false,
  },
  PropertyDescriptorMap: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PropertyDescriptorMap',
    writeable: false,
  },
  Object: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Object',
    writeable: false,
  },
  ObjectConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ObjectConstructor',
    writeable: false,
  },
  Function: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Function',
    writeable: false,
  },
  FunctionConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'FunctionConstructor',
    writeable: false,
  },
  ThisParameterType: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ThisParameterType',
    writeable: false,
  },
  OmitThisParameter: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'OmitThisParameter',
    writeable: false,
  },
  CallableFunction: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CallableFunction',
    writeable: false,
  },
  NewableFunction: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'NewableFunction',
    writeable: false,
  },
  IArguments: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'IArguments',
    writeable: false,
  },
  String: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'String',
    writeable: false,
  },
  StringConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'StringConstructor',
    writeable: false,
  },
  Boolean: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Boolean',
    writeable: false,
  },
  BooleanConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'BooleanConstructor',
    writeable: false,
  },
  Number: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Number',
    writeable: false,
  },
  NumberConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'NumberConstructor',
    writeable: false,
  },
  TemplateStringsArray: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'TemplateStringsArray',
    writeable: false,
  },
  ImportMeta: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ImportMeta',
    writeable: false,
  },
  Math: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Math',
    writeable: false,
  },
  Date: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Date',
    writeable: false,
  },
  DateConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'DateConstructor',
    writeable: false,
  },
  RegExpMatchArray: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'RegExpMatchArray',
    writeable: false,
  },
  RegExpExecArray: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'RegExpExecArray',
    writeable: false,
  },
  RegExp: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'RegExp',
    writeable: false,
  },
  RegExpConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'RegExpConstructor',
    writeable: false,
  },
  Error: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Error',
    writeable: false,
  },
  ErrorConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ErrorConstructor',
    writeable: false,
  },
  EvalError: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'EvalError',
    writeable: false,
  },
  EvalErrorConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'EvalErrorConstructor',
    writeable: false,
  },
  RangeError: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'RangeError',
    writeable: false,
  },
  RangeErrorConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'RangeErrorConstructor',
    writeable: false,
  },
  ReferenceError: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'ReferenceError',
    writeable: false,
  },
  ReferenceErrorConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ReferenceErrorConstructor',
    writeable: false,
  },
  SyntaxError: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'SyntaxError',
    writeable: false,
  },
  SyntaxErrorConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'SyntaxErrorConstructor',
    writeable: false,
  },
  TypeError: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'TypeError',
    writeable: false,
  },
  TypeErrorConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'TypeErrorConstructor',
    writeable: false,
  },
  URIError: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'URIError',
    writeable: false,
  },
  URIErrorConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'URIErrorConstructor',
    writeable: false,
  },
  JSON: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'JSON',
    writeable: false,
  },
  ReadonlyArray: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ReadonlyArray',
    writeable: false,
  },
  ConcatArray: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ConcatArray',
    writeable: false,
  },
  Array: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Array',
    writeable: false,
  },
  ArrayConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ArrayConstructor',
    writeable: false,
  },
  TypedPropertyDescriptor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'TypedPropertyDescriptor',
    writeable: false,
  },
  ClassDecorator: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ClassDecorator',
    writeable: false,
  },
  PropertyDecorator: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PropertyDecorator',
    writeable: false,
  },
  MethodDecorator: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'MethodDecorator',
    writeable: false,
  },
  ParameterDecorator: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ParameterDecorator',
    writeable: false,
  },
  PromiseConstructorLike: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PromiseConstructorLike',
    writeable: false,
  },
  PromiseLike: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PromiseLike',
    writeable: false,
  },
  Promise: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Promise',
    writeable: false,
  },
  ArrayLike: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ArrayLike',
    writeable: false,
  },
  Partial: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Partial',
    writeable: false,
  },
  Required: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Required',
    writeable: false,
  },
  Readonly: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Readonly',
    writeable: false,
  },
  Pick: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Pick',
    writeable: false,
  },
  Record: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Record',
    writeable: false,
  },
  Exclude: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Exclude',
    writeable: false,
  },
  Extract: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Extract',
    writeable: false,
  },
  Omit: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Omit',
    writeable: false,
  },
  NonNullable: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'NonNullable',
    writeable: false,
  },
  Parameters: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Parameters',
    writeable: false,
  },
  ConstructorParameters: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ConstructorParameters',
    writeable: false,
  },
  ReturnType: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ReturnType',
    writeable: false,
  },
  InstanceType: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'InstanceType',
    writeable: false,
  },
  ThisType: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ThisType',
    writeable: false,
  },
  ArrayBuffer: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'ArrayBuffer',
    writeable: false,
  },
  ArrayBufferTypes: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ArrayBufferTypes',
    writeable: false,
  },
  ArrayBufferLike: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ArrayBufferLike',
    writeable: false,
  },
  ArrayBufferConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ArrayBufferConstructor',
    writeable: false,
  },
  ArrayBufferView: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ArrayBufferView',
    writeable: false,
  },
  DataView: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'DataView',
    writeable: false,
  },
  DataViewConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'DataViewConstructor',
    writeable: false,
  },
  Int8Array: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Int8Array',
    writeable: false,
  },
  Int8ArrayConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Int8ArrayConstructor',
    writeable: false,
  },
  Uint8Array: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Uint8Array',
    writeable: false,
  },
  Uint8ArrayConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Uint8ArrayConstructor',
    writeable: false,
  },
  Uint8ClampedArray: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Uint8ClampedArray',
    writeable: false,
  },
  Uint8ClampedArrayConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Uint8ClampedArrayConstructor',
    writeable: false,
  },
  Int16Array: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Int16Array',
    writeable: false,
  },
  Int16ArrayConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Int16ArrayConstructor',
    writeable: false,
  },
  Uint16Array: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Uint16Array',
    writeable: false,
  },
  Uint16ArrayConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Uint16ArrayConstructor',
    writeable: false,
  },
  Int32Array: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Int32Array',
    writeable: false,
  },
  Int32ArrayConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Int32ArrayConstructor',
    writeable: false,
  },
  Uint32Array: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Uint32Array',
    writeable: false,
  },
  Uint32ArrayConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Uint32ArrayConstructor',
    writeable: false,
  },
  Float32Array: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Float32Array',
    writeable: false,
  },
  Float32ArrayConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Float32ArrayConstructor',
    writeable: false,
  },
  Float64Array: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Float64Array',
    writeable: false,
  },
  Float64ArrayConstructor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Float64ArrayConstructor',
    writeable: false,
  },
  Intl: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Intl',
    writeable: false,
  },
};
