// THIS CODE WAS AUTOMATICALLY GENERATED
// DO NOT EDIT THIS CODE BY HAND
// YOU CAN REGENERATE IT USING yarn generate:lib

export const webworker = {
  AddEventListenerOptions: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'AddEventListenerOptions',
    writeable: false,
  },
  AesCbcParams: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'AesCbcParams',
    writeable: false,
  },
  AesCtrParams: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'AesCtrParams',
    writeable: false,
  },
  AesDerivedKeyParams: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'AesDerivedKeyParams',
    writeable: false,
  },
  AesGcmParams: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'AesGcmParams',
    writeable: false,
  },
  AesKeyAlgorithm: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'AesKeyAlgorithm',
    writeable: false,
  },
  AesKeyGenParams: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'AesKeyGenParams',
    writeable: false,
  },
  Algorithm: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Algorithm',
    writeable: false,
  },
  BlobPropertyBag: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'BlobPropertyBag',
    writeable: false,
  },
  CacheQueryOptions: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CacheQueryOptions',
    writeable: false,
  },
  CanvasRenderingContext2DSettings: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasRenderingContext2DSettings',
    writeable: false,
  },
  ClientQueryOptions: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ClientQueryOptions',
    writeable: false,
  },
  CloseEventInit: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CloseEventInit',
    writeable: false,
  },
  CryptoKeyPair: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CryptoKeyPair',
    writeable: false,
  },
  CustomEventInit: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CustomEventInit',
    writeable: false,
  },
  DOMMatrix2DInit: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'DOMMatrix2DInit',
    writeable: false,
  },
  DOMMatrixInit: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'DOMMatrixInit',
    writeable: false,
  },
  DOMPointInit: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'DOMPointInit',
    writeable: false,
  },
  DOMQuadInit: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'DOMQuadInit',
    writeable: false,
  },
  DOMRectInit: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'DOMRectInit',
    writeable: false,
  },
  DevicePermissionDescriptor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'DevicePermissionDescriptor',
    writeable: false,
  },
  EcKeyGenParams: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'EcKeyGenParams',
    writeable: false,
  },
  EcKeyImportParams: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'EcKeyImportParams',
    writeable: false,
  },
  EcdhKeyDeriveParams: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'EcdhKeyDeriveParams',
    writeable: false,
  },
  EcdsaParams: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'EcdsaParams',
    writeable: false,
  },
  ErrorEventInit: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ErrorEventInit',
    writeable: false,
  },
  EventInit: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'EventInit',
    writeable: false,
  },
  EventListenerOptions: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'EventListenerOptions',
    writeable: false,
  },
  EventSourceInit: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'EventSourceInit',
    writeable: false,
  },
  ExtendableEventInit: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ExtendableEventInit',
    writeable: false,
  },
  ExtendableMessageEventInit: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ExtendableMessageEventInit',
    writeable: false,
  },
  FetchEventInit: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'FetchEventInit',
    writeable: false,
  },
  FilePropertyBag: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'FilePropertyBag',
    writeable: false,
  },
  GetNotificationOptions: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'GetNotificationOptions',
    writeable: false,
  },
  HmacImportParams: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'HmacImportParams',
    writeable: false,
  },
  HmacKeyGenParams: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'HmacKeyGenParams',
    writeable: false,
  },
  IDBIndexParameters: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'IDBIndexParameters',
    writeable: false,
  },
  IDBObjectStoreParameters: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'IDBObjectStoreParameters',
    writeable: false,
  },
  IDBVersionChangeEventInit: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'IDBVersionChangeEventInit',
    writeable: false,
  },
  ImageBitmapOptions: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ImageBitmapOptions',
    writeable: false,
  },
  ImageBitmapRenderingContextSettings: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ImageBitmapRenderingContextSettings',
    writeable: false,
  },
  ImageEncodeOptions: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ImageEncodeOptions',
    writeable: false,
  },
  JsonWebKey: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'JsonWebKey',
    writeable: false,
  },
  KeyAlgorithm: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'KeyAlgorithm',
    writeable: false,
  },
  MessageEventInit: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'MessageEventInit',
    writeable: false,
  },
  MidiPermissionDescriptor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'MidiPermissionDescriptor',
    writeable: false,
  },
  MultiCacheQueryOptions: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'MultiCacheQueryOptions',
    writeable: false,
  },
  NavigationPreloadState: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'NavigationPreloadState',
    writeable: false,
  },
  NotificationAction: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'NotificationAction',
    writeable: false,
  },
  NotificationEventInit: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'NotificationEventInit',
    writeable: false,
  },
  NotificationOptions: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'NotificationOptions',
    writeable: false,
  },
  Pbkdf2Params: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Pbkdf2Params',
    writeable: false,
  },
  PerformanceObserverInit: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PerformanceObserverInit',
    writeable: false,
  },
  PermissionDescriptor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PermissionDescriptor',
    writeable: false,
  },
  PipeOptions: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PipeOptions',
    writeable: false,
  },
  PostMessageOptions: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PostMessageOptions',
    writeable: false,
  },
  ProgressEventInit: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ProgressEventInit',
    writeable: false,
  },
  PromiseRejectionEventInit: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PromiseRejectionEventInit',
    writeable: false,
  },
  PushEventInit: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PushEventInit',
    writeable: false,
  },
  PushPermissionDescriptor: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PushPermissionDescriptor',
    writeable: false,
  },
  PushSubscriptionChangeEventInit: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PushSubscriptionChangeEventInit',
    writeable: false,
  },
  PushSubscriptionJSON: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PushSubscriptionJSON',
    writeable: false,
  },
  PushSubscriptionOptionsInit: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PushSubscriptionOptionsInit',
    writeable: false,
  },
  QueuingStrategy: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'QueuingStrategy',
    writeable: false,
  },
  ReadableStreamReadDoneResult: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ReadableStreamReadDoneResult',
    writeable: false,
  },
  ReadableStreamReadValueResult: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ReadableStreamReadValueResult',
    writeable: false,
  },
  RegistrationOptions: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'RegistrationOptions',
    writeable: false,
  },
  RequestInit: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'RequestInit',
    writeable: false,
  },
  ResponseInit: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ResponseInit',
    writeable: false,
  },
  RsaHashedImportParams: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'RsaHashedImportParams',
    writeable: false,
  },
  RsaHashedKeyGenParams: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'RsaHashedKeyGenParams',
    writeable: false,
  },
  RsaKeyGenParams: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'RsaKeyGenParams',
    writeable: false,
  },
  RsaOaepParams: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'RsaOaepParams',
    writeable: false,
  },
  RsaOtherPrimesInfo: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'RsaOtherPrimesInfo',
    writeable: false,
  },
  RsaPssParams: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'RsaPssParams',
    writeable: false,
  },
  StorageEstimate: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'StorageEstimate',
    writeable: false,
  },
  SyncEventInit: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'SyncEventInit',
    writeable: false,
  },
  TextDecodeOptions: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'TextDecodeOptions',
    writeable: false,
  },
  TextDecoderOptions: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'TextDecoderOptions',
    writeable: false,
  },
  TextEncoderEncodeIntoResult: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'TextEncoderEncodeIntoResult',
    writeable: false,
  },
  Transformer: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Transformer',
    writeable: false,
  },
  UnderlyingByteSource: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'UnderlyingByteSource',
    writeable: false,
  },
  UnderlyingSink: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'UnderlyingSink',
    writeable: false,
  },
  UnderlyingSource: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'UnderlyingSource',
    writeable: false,
  },
  WebGLContextAttributes: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WebGLContextAttributes',
    writeable: false,
  },
  WebGLContextEventInit: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WebGLContextEventInit',
    writeable: false,
  },
  WorkerOptions: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WorkerOptions',
    writeable: false,
  },
  EventListener: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'EventListener',
    writeable: false,
  },
  ANGLE_instanced_arrays: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ANGLE_instanced_arrays',
    writeable: false,
  },
  AbortController: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'AbortController',
    writeable: false,
  },
  AbortSignalEventMap: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'AbortSignalEventMap',
    writeable: false,
  },
  AbortSignal: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'AbortSignal',
    writeable: false,
  },
  AbstractWorkerEventMap: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'AbstractWorkerEventMap',
    writeable: false,
  },
  AbstractWorker: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'AbstractWorker',
    writeable: false,
  },
  AesCfbParams: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'AesCfbParams',
    writeable: false,
  },
  AesCmacParams: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'AesCmacParams',
    writeable: false,
  },
  AnimationFrameProvider: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'AnimationFrameProvider',
    writeable: false,
  },
  Blob: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Blob',
    writeable: false,
  },
  Body: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Body',
    writeable: false,
  },
  BroadcastChannelEventMap: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'BroadcastChannelEventMap',
    writeable: false,
  },
  BroadcastChannel: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'BroadcastChannel',
    writeable: false,
  },
  ByteLengthQueuingStrategy: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'ByteLengthQueuingStrategy',
    writeable: false,
  },
  Cache: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Cache',
    writeable: false,
  },
  CacheStorage: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'CacheStorage',
    writeable: false,
  },
  CanvasCompositing: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasCompositing',
    writeable: false,
  },
  CanvasDrawImage: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasDrawImage',
    writeable: false,
  },
  CanvasDrawPath: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasDrawPath',
    writeable: false,
  },
  CanvasFillStrokeStyles: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasFillStrokeStyles',
    writeable: false,
  },
  CanvasFilters: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasFilters',
    writeable: false,
  },
  CanvasGradient: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'CanvasGradient',
    writeable: false,
  },
  CanvasImageData: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasImageData',
    writeable: false,
  },
  CanvasImageSmoothing: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasImageSmoothing',
    writeable: false,
  },
  CanvasPath: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasPath',
    writeable: false,
  },
  CanvasPathDrawingStyles: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasPathDrawingStyles',
    writeable: false,
  },
  CanvasPattern: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'CanvasPattern',
    writeable: false,
  },
  CanvasRect: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasRect',
    writeable: false,
  },
  CanvasShadowStyles: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasShadowStyles',
    writeable: false,
  },
  CanvasState: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasState',
    writeable: false,
  },
  CanvasText: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasText',
    writeable: false,
  },
  CanvasTextDrawingStyles: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasTextDrawingStyles',
    writeable: false,
  },
  CanvasTransform: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasTransform',
    writeable: false,
  },
  Client: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Client',
    writeable: false,
  },
  Clients: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Clients',
    writeable: false,
  },
  CloseEvent: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'CloseEvent',
    writeable: false,
  },
  ConcatParams: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ConcatParams',
    writeable: false,
  },
  CountQueuingStrategy: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'CountQueuingStrategy',
    writeable: false,
  },
  Crypto: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Crypto',
    writeable: false,
  },
  CryptoKey: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'CryptoKey',
    writeable: false,
  },
  CustomEvent: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'CustomEvent',
    writeable: false,
  },
  DOMException: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'DOMException',
    writeable: false,
  },
  DOMMatrix: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'DOMMatrix',
    writeable: false,
  },
  DOMMatrixReadOnly: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'DOMMatrixReadOnly',
    writeable: false,
  },
  DOMPoint: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'DOMPoint',
    writeable: false,
  },
  DOMPointReadOnly: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'DOMPointReadOnly',
    writeable: false,
  },
  DOMQuad: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'DOMQuad',
    writeable: false,
  },
  DOMRect: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'DOMRect',
    writeable: false,
  },
  DOMRectReadOnly: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'DOMRectReadOnly',
    writeable: false,
  },
  DOMStringList: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'DOMStringList',
    writeable: false,
  },
  DedicatedWorkerGlobalScopeEventMap: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'DedicatedWorkerGlobalScopeEventMap',
    writeable: false,
  },
  DedicatedWorkerGlobalScope: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'DedicatedWorkerGlobalScope',
    writeable: false,
  },
  DhImportKeyParams: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'DhImportKeyParams',
    writeable: false,
  },
  DhKeyAlgorithm: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'DhKeyAlgorithm',
    writeable: false,
  },
  DhKeyDeriveParams: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'DhKeyDeriveParams',
    writeable: false,
  },
  DhKeyGenParams: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'DhKeyGenParams',
    writeable: false,
  },
  EXT_blend_minmax: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'EXT_blend_minmax',
    writeable: false,
  },
  EXT_frag_depth: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'EXT_frag_depth',
    writeable: false,
  },
  EXT_sRGB: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'EXT_sRGB',
    writeable: false,
  },
  EXT_shader_texture_lod: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'EXT_shader_texture_lod',
    writeable: false,
  },
  EXT_texture_filter_anisotropic: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'EXT_texture_filter_anisotropic',
    writeable: false,
  },
  ErrorEvent: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'ErrorEvent',
    writeable: false,
  },
  Event: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Event',
    writeable: false,
  },
  EventListenerObject: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'EventListenerObject',
    writeable: false,
  },
  EventSourceEventMap: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'EventSourceEventMap',
    writeable: false,
  },
  EventSource: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'EventSource',
    writeable: false,
  },
  EventTarget: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'EventTarget',
    writeable: false,
  },
  ExtendableEvent: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'ExtendableEvent',
    writeable: false,
  },
  ExtendableMessageEvent: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'ExtendableMessageEvent',
    writeable: false,
  },
  FetchEvent: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'FetchEvent',
    writeable: false,
  },
  File: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'File',
    writeable: false,
  },
  FileList: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'FileList',
    writeable: false,
  },
  FileReaderEventMap: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'FileReaderEventMap',
    writeable: false,
  },
  FileReader: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'FileReader',
    writeable: false,
  },
  FileReaderSync: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'FileReaderSync',
    writeable: false,
  },
  FormData: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'FormData',
    writeable: false,
  },
  GenericTransformStream: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'GenericTransformStream',
    writeable: false,
  },
  Headers: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Headers',
    writeable: false,
  },
  HkdfCtrParams: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'HkdfCtrParams',
    writeable: false,
  },
  IDBArrayKey: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'IDBArrayKey',
    writeable: false,
  },
  IDBCursor: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'IDBCursor',
    writeable: false,
  },
  IDBCursorWithValue: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'IDBCursorWithValue',
    writeable: false,
  },
  IDBDatabaseEventMap: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'IDBDatabaseEventMap',
    writeable: false,
  },
  IDBDatabase: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'IDBDatabase',
    writeable: false,
  },
  IDBFactory: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'IDBFactory',
    writeable: false,
  },
  IDBIndex: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'IDBIndex',
    writeable: false,
  },
  IDBKeyRange: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'IDBKeyRange',
    writeable: false,
  },
  IDBObjectStore: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'IDBObjectStore',
    writeable: false,
  },
  IDBOpenDBRequestEventMap: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'IDBOpenDBRequestEventMap',
    writeable: false,
  },
  IDBOpenDBRequest: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'IDBOpenDBRequest',
    writeable: false,
  },
  IDBRequestEventMap: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'IDBRequestEventMap',
    writeable: false,
  },
  IDBRequest: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'IDBRequest',
    writeable: false,
  },
  IDBTransactionEventMap: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'IDBTransactionEventMap',
    writeable: false,
  },
  IDBTransaction: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'IDBTransaction',
    writeable: false,
  },
  IDBVersionChangeEvent: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'IDBVersionChangeEvent',
    writeable: false,
  },
  ImageBitmap: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'ImageBitmap',
    writeable: false,
  },
  ImageBitmapRenderingContext: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'ImageBitmapRenderingContext',
    writeable: false,
  },
  ImageData: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'ImageData',
    writeable: false,
  },
  MessageChannel: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'MessageChannel',
    writeable: false,
  },
  MessageEvent: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'MessageEvent',
    writeable: false,
  },
  MessagePortEventMap: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'MessagePortEventMap',
    writeable: false,
  },
  MessagePort: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'MessagePort',
    writeable: false,
  },
  NavigationPreloadManager: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'NavigationPreloadManager',
    writeable: false,
  },
  NavigatorConcurrentHardware: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'NavigatorConcurrentHardware',
    writeable: false,
  },
  NavigatorID: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'NavigatorID',
    writeable: false,
  },
  NavigatorLanguage: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'NavigatorLanguage',
    writeable: false,
  },
  NavigatorOnLine: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'NavigatorOnLine',
    writeable: false,
  },
  NavigatorStorage: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'NavigatorStorage',
    writeable: false,
  },
  NotificationEventMap: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'NotificationEventMap',
    writeable: false,
  },
  Notification: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Notification',
    writeable: false,
  },
  NotificationEvent: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'NotificationEvent',
    writeable: false,
  },
  OES_element_index_uint: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'OES_element_index_uint',
    writeable: false,
  },
  OES_standard_derivatives: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'OES_standard_derivatives',
    writeable: false,
  },
  OES_texture_float: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'OES_texture_float',
    writeable: false,
  },
  OES_texture_float_linear: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'OES_texture_float_linear',
    writeable: false,
  },
  OES_texture_half_float: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'OES_texture_half_float',
    writeable: false,
  },
  OES_texture_half_float_linear: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'OES_texture_half_float_linear',
    writeable: false,
  },
  OES_vertex_array_object: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'OES_vertex_array_object',
    writeable: false,
  },
  OffscreenCanvas: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'OffscreenCanvas',
    writeable: false,
  },
  OffscreenCanvasRenderingContext2D: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'OffscreenCanvasRenderingContext2D',
    writeable: false,
  },
  Path2D: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Path2D',
    writeable: false,
  },
  PerformanceEventMap: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PerformanceEventMap',
    writeable: false,
  },
  Performance: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Performance',
    writeable: false,
  },
  PerformanceEntry: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'PerformanceEntry',
    writeable: false,
  },
  PerformanceMark: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'PerformanceMark',
    writeable: false,
  },
  PerformanceMeasure: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'PerformanceMeasure',
    writeable: false,
  },
  PerformanceObserver: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'PerformanceObserver',
    writeable: false,
  },
  PerformanceObserverEntryList: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'PerformanceObserverEntryList',
    writeable: false,
  },
  PerformanceResourceTiming: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'PerformanceResourceTiming',
    writeable: false,
  },
  PermissionStatusEventMap: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PermissionStatusEventMap',
    writeable: false,
  },
  PermissionStatus: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'PermissionStatus',
    writeable: false,
  },
  Permissions: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Permissions',
    writeable: false,
  },
  ProgressEvent: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'ProgressEvent',
    writeable: false,
  },
  PromiseRejectionEvent: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'PromiseRejectionEvent',
    writeable: false,
  },
  PushEvent: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'PushEvent',
    writeable: false,
  },
  PushManager: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'PushManager',
    writeable: false,
  },
  PushMessageData: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'PushMessageData',
    writeable: false,
  },
  PushSubscription: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'PushSubscription',
    writeable: false,
  },
  PushSubscriptionChangeEvent: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'PushSubscriptionChangeEvent',
    writeable: false,
  },
  PushSubscriptionOptions: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'PushSubscriptionOptions',
    writeable: false,
  },
  ReadableByteStreamController: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ReadableByteStreamController',
    writeable: false,
  },
  ReadableStream: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'ReadableStream',
    writeable: false,
  },
  ReadableStreamBYOBReader: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ReadableStreamBYOBReader',
    writeable: false,
  },
  ReadableStreamBYOBRequest: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ReadableStreamBYOBRequest',
    writeable: false,
  },
  ReadableStreamDefaultController: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ReadableStreamDefaultController',
    writeable: false,
  },
  ReadableStreamDefaultReader: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ReadableStreamDefaultReader',
    writeable: false,
  },
  ReadableStreamReader: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'ReadableStreamReader',
    writeable: false,
  },
  Request: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Request',
    writeable: false,
  },
  Response: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Response',
    writeable: false,
  },
  ServiceWorkerEventMap: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ServiceWorkerEventMap',
    writeable: false,
  },
  ServiceWorker: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'ServiceWorker',
    writeable: false,
  },
  ServiceWorkerContainerEventMap: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ServiceWorkerContainerEventMap',
    writeable: false,
  },
  ServiceWorkerContainer: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'ServiceWorkerContainer',
    writeable: false,
  },
  ServiceWorkerGlobalScopeEventMap: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ServiceWorkerGlobalScopeEventMap',
    writeable: false,
  },
  ServiceWorkerGlobalScope: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'ServiceWorkerGlobalScope',
    writeable: false,
  },
  ServiceWorkerRegistrationEventMap: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ServiceWorkerRegistrationEventMap',
    writeable: false,
  },
  ServiceWorkerRegistration: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'ServiceWorkerRegistration',
    writeable: false,
  },
  SharedWorker: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'SharedWorker',
    writeable: false,
  },
  SharedWorkerGlobalScopeEventMap: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'SharedWorkerGlobalScopeEventMap',
    writeable: false,
  },
  SharedWorkerGlobalScope: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'SharedWorkerGlobalScope',
    writeable: false,
  },
  StorageManager: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'StorageManager',
    writeable: false,
  },
  SubtleCrypto: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'SubtleCrypto',
    writeable: false,
  },
  SyncEvent: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'SyncEvent',
    writeable: false,
  },
  SyncManager: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'SyncManager',
    writeable: false,
  },
  TextDecoder: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'TextDecoder',
    writeable: false,
  },
  TextDecoderCommon: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'TextDecoderCommon',
    writeable: false,
  },
  TextDecoderStream: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'TextDecoderStream',
    writeable: false,
  },
  TextEncoder: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'TextEncoder',
    writeable: false,
  },
  TextEncoderCommon: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'TextEncoderCommon',
    writeable: false,
  },
  TextEncoderStream: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'TextEncoderStream',
    writeable: false,
  },
  TextMetrics: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'TextMetrics',
    writeable: false,
  },
  TransformStream: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'TransformStream',
    writeable: false,
  },
  TransformStreamDefaultController: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'TransformStreamDefaultController',
    writeable: false,
  },
  URL: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'URL',
    writeable: false,
  },
  URLSearchParams: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'URLSearchParams',
    writeable: false,
  },
  WEBGL_color_buffer_float: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WEBGL_color_buffer_float',
    writeable: false,
  },
  WEBGL_compressed_texture_astc: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WEBGL_compressed_texture_astc',
    writeable: false,
  },
  WEBGL_compressed_texture_s3tc: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WEBGL_compressed_texture_s3tc',
    writeable: false,
  },
  WEBGL_compressed_texture_s3tc_srgb: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WEBGL_compressed_texture_s3tc_srgb',
    writeable: false,
  },
  WEBGL_debug_renderer_info: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WEBGL_debug_renderer_info',
    writeable: false,
  },
  WEBGL_debug_shaders: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WEBGL_debug_shaders',
    writeable: false,
  },
  WEBGL_depth_texture: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WEBGL_depth_texture',
    writeable: false,
  },
  WEBGL_draw_buffers: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WEBGL_draw_buffers',
    writeable: false,
  },
  WEBGL_lose_context: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WEBGL_lose_context',
    writeable: false,
  },
  WebGL2RenderingContext: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WebGL2RenderingContext',
    writeable: false,
  },
  WebGL2RenderingContextBase: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WebGL2RenderingContextBase',
    writeable: false,
  },
  WebGL2RenderingContextOverloads: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WebGL2RenderingContextOverloads',
    writeable: false,
  },
  WebGLActiveInfo: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WebGLActiveInfo',
    writeable: false,
  },
  WebGLBuffer: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WebGLBuffer',
    writeable: false,
  },
  WebGLContextEvent: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WebGLContextEvent',
    writeable: false,
  },
  WebGLFramebuffer: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WebGLFramebuffer',
    writeable: false,
  },
  WebGLObject: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WebGLObject',
    writeable: false,
  },
  WebGLProgram: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WebGLProgram',
    writeable: false,
  },
  WebGLQuery: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WebGLQuery',
    writeable: false,
  },
  WebGLRenderbuffer: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WebGLRenderbuffer',
    writeable: false,
  },
  WebGLRenderingContext: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WebGLRenderingContext',
    writeable: false,
  },
  WebGLRenderingContextBase: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WebGLRenderingContextBase',
    writeable: false,
  },
  WebGLRenderingContextOverloads: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WebGLRenderingContextOverloads',
    writeable: false,
  },
  WebGLSampler: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WebGLSampler',
    writeable: false,
  },
  WebGLShader: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WebGLShader',
    writeable: false,
  },
  WebGLShaderPrecisionFormat: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WebGLShaderPrecisionFormat',
    writeable: false,
  },
  WebGLSync: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WebGLSync',
    writeable: false,
  },
  WebGLTexture: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WebGLTexture',
    writeable: false,
  },
  WebGLTransformFeedback: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WebGLTransformFeedback',
    writeable: false,
  },
  WebGLUniformLocation: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WebGLUniformLocation',
    writeable: false,
  },
  WebGLVertexArrayObject: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WebGLVertexArrayObject',
    writeable: false,
  },
  WebGLVertexArrayObjectOES: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WebGLVertexArrayObjectOES',
    writeable: false,
  },
  WebSocketEventMap: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WebSocketEventMap',
    writeable: false,
  },
  WebSocket: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WebSocket',
    writeable: false,
  },
  WindowClient: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WindowClient',
    writeable: false,
  },
  WindowOrWorkerGlobalScope: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WindowOrWorkerGlobalScope',
    writeable: false,
  },
  WorkerEventMap: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WorkerEventMap',
    writeable: false,
  },
  Worker: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'Worker',
    writeable: false,
  },
  WorkerGlobalScopeEventMap: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WorkerGlobalScopeEventMap',
    writeable: false,
  },
  WorkerGlobalScope: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WorkerGlobalScope',
    writeable: false,
  },
  WorkerLocation: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WorkerLocation',
    writeable: false,
  },
  WorkerNavigator: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WorkerNavigator',
    writeable: false,
  },
  WritableStream: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WritableStream',
    writeable: false,
  },
  WritableStreamDefaultController: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WritableStreamDefaultController',
    writeable: false,
  },
  WritableStreamDefaultWriter: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WritableStreamDefaultWriter',
    writeable: false,
  },
  XMLHttpRequestEventMap: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'XMLHttpRequestEventMap',
    writeable: false,
  },
  XMLHttpRequest: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'XMLHttpRequest',
    writeable: false,
  },
  XMLHttpRequestEventTargetEventMap: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'XMLHttpRequestEventTargetEventMap',
    writeable: false,
  },
  XMLHttpRequestEventTarget: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'XMLHttpRequestEventTarget',
    writeable: false,
  },
  XMLHttpRequestUpload: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'XMLHttpRequestUpload',
    writeable: false,
  },
  EventListenerOrEventListenerObject: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'EventListenerOrEventListenerObject',
    writeable: false,
  },
  Console: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Console',
    writeable: false,
  },
  WebAssembly: {
    isTypeVariable: true,
    isValueVariable: true,
    name: 'WebAssembly',
    writeable: false,
  },
  FrameRequestCallback: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'FrameRequestCallback',
    writeable: false,
  },
  OnErrorEventHandlerNonNull: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'OnErrorEventHandlerNonNull',
    writeable: false,
  },
  PerformanceObserverCallback: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PerformanceObserverCallback',
    writeable: false,
  },
  QueuingStrategySizeCallback: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'QueuingStrategySizeCallback',
    writeable: false,
  },
  ReadableByteStreamControllerCallback: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ReadableByteStreamControllerCallback',
    writeable: false,
  },
  ReadableStreamDefaultControllerCallback: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ReadableStreamDefaultControllerCallback',
    writeable: false,
  },
  ReadableStreamErrorCallback: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ReadableStreamErrorCallback',
    writeable: false,
  },
  TransformStreamDefaultControllerCallback: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'TransformStreamDefaultControllerCallback',
    writeable: false,
  },
  TransformStreamDefaultControllerTransformCallback: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'TransformStreamDefaultControllerTransformCallback',
    writeable: false,
  },
  VoidFunction: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'VoidFunction',
    writeable: false,
  },
  WritableStreamDefaultControllerCloseCallback: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WritableStreamDefaultControllerCloseCallback',
    writeable: false,
  },
  WritableStreamDefaultControllerStartCallback: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WritableStreamDefaultControllerStartCallback',
    writeable: false,
  },
  WritableStreamDefaultControllerWriteCallback: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WritableStreamDefaultControllerWriteCallback',
    writeable: false,
  },
  WritableStreamErrorCallback: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WritableStreamErrorCallback',
    writeable: false,
  },
  HeadersInit: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'HeadersInit',
    writeable: false,
  },
  BodyInit: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'BodyInit',
    writeable: false,
  },
  RequestInfo: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'RequestInfo',
    writeable: false,
  },
  BlobPart: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'BlobPart',
    writeable: false,
  },
  DOMHighResTimeStamp: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'DOMHighResTimeStamp',
    writeable: false,
  },
  CanvasImageSource: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasImageSource',
    writeable: false,
  },
  OffscreenRenderingContext: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'OffscreenRenderingContext',
    writeable: false,
  },
  MessageEventSource: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'MessageEventSource',
    writeable: false,
  },
  ImageBitmapSource: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ImageBitmapSource',
    writeable: false,
  },
  OnErrorEventHandler: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'OnErrorEventHandler',
    writeable: false,
  },
  TimerHandler: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'TimerHandler',
    writeable: false,
  },
  PerformanceEntryList: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PerformanceEntryList',
    writeable: false,
  },
  PushMessageDataInit: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PushMessageDataInit',
    writeable: false,
  },
  ReadableStreamReadResult: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ReadableStreamReadResult',
    writeable: false,
  },
  VibratePattern: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'VibratePattern',
    writeable: false,
  },
  AlgorithmIdentifier: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'AlgorithmIdentifier',
    writeable: false,
  },
  HashAlgorithmIdentifier: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'HashAlgorithmIdentifier',
    writeable: false,
  },
  BigInteger: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'BigInteger',
    writeable: false,
  },
  NamedCurve: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'NamedCurve',
    writeable: false,
  },
  GLenum: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'GLenum',
    writeable: false,
  },
  GLboolean: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'GLboolean',
    writeable: false,
  },
  GLbitfield: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'GLbitfield',
    writeable: false,
  },
  GLint: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'GLint',
    writeable: false,
  },
  GLsizei: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'GLsizei',
    writeable: false,
  },
  GLintptr: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'GLintptr',
    writeable: false,
  },
  GLsizeiptr: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'GLsizeiptr',
    writeable: false,
  },
  GLuint: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'GLuint',
    writeable: false,
  },
  GLfloat: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'GLfloat',
    writeable: false,
  },
  GLclampf: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'GLclampf',
    writeable: false,
  },
  TexImageSource: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'TexImageSource',
    writeable: false,
  },
  Float32List: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Float32List',
    writeable: false,
  },
  Int32List: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Int32List',
    writeable: false,
  },
  GLint64: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'GLint64',
    writeable: false,
  },
  GLuint64: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'GLuint64',
    writeable: false,
  },
  Uint32List: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Uint32List',
    writeable: false,
  },
  BufferSource: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'BufferSource',
    writeable: false,
  },
  DOMTimeStamp: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'DOMTimeStamp',
    writeable: false,
  },
  FormDataEntryValue: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'FormDataEntryValue',
    writeable: false,
  },
  IDBValidKey: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'IDBValidKey',
    writeable: false,
  },
  Transferable: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'Transferable',
    writeable: false,
  },
  BinaryType: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'BinaryType',
    writeable: false,
  },
  CanvasDirection: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasDirection',
    writeable: false,
  },
  CanvasFillRule: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasFillRule',
    writeable: false,
  },
  CanvasLineCap: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasLineCap',
    writeable: false,
  },
  CanvasLineJoin: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasLineJoin',
    writeable: false,
  },
  CanvasTextAlign: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasTextAlign',
    writeable: false,
  },
  CanvasTextBaseline: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'CanvasTextBaseline',
    writeable: false,
  },
  ClientTypes: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ClientTypes',
    writeable: false,
  },
  ColorSpaceConversion: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ColorSpaceConversion',
    writeable: false,
  },
  EndingType: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'EndingType',
    writeable: false,
  },
  FrameType: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'FrameType',
    writeable: false,
  },
  IDBCursorDirection: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'IDBCursorDirection',
    writeable: false,
  },
  IDBRequestReadyState: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'IDBRequestReadyState',
    writeable: false,
  },
  IDBTransactionMode: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'IDBTransactionMode',
    writeable: false,
  },
  ImageOrientation: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ImageOrientation',
    writeable: false,
  },
  ImageSmoothingQuality: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ImageSmoothingQuality',
    writeable: false,
  },
  KeyFormat: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'KeyFormat',
    writeable: false,
  },
  KeyType: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'KeyType',
    writeable: false,
  },
  KeyUsage: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'KeyUsage',
    writeable: false,
  },
  NotificationDirection: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'NotificationDirection',
    writeable: false,
  },
  NotificationPermission: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'NotificationPermission',
    writeable: false,
  },
  OffscreenRenderingContextId: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'OffscreenRenderingContextId',
    writeable: false,
  },
  PermissionName: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PermissionName',
    writeable: false,
  },
  PermissionState: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PermissionState',
    writeable: false,
  },
  PremultiplyAlpha: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PremultiplyAlpha',
    writeable: false,
  },
  PushEncryptionKeyName: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PushEncryptionKeyName',
    writeable: false,
  },
  PushPermissionState: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'PushPermissionState',
    writeable: false,
  },
  ReferrerPolicy: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ReferrerPolicy',
    writeable: false,
  },
  RequestCache: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'RequestCache',
    writeable: false,
  },
  RequestCredentials: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'RequestCredentials',
    writeable: false,
  },
  RequestDestination: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'RequestDestination',
    writeable: false,
  },
  RequestMode: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'RequestMode',
    writeable: false,
  },
  RequestRedirect: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'RequestRedirect',
    writeable: false,
  },
  ResizeQuality: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ResizeQuality',
    writeable: false,
  },
  ResponseType: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ResponseType',
    writeable: false,
  },
  ServiceWorkerState: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ServiceWorkerState',
    writeable: false,
  },
  ServiceWorkerUpdateViaCache: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'ServiceWorkerUpdateViaCache',
    writeable: false,
  },
  VisibilityState: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'VisibilityState',
    writeable: false,
  },
  WebGLPowerPreference: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WebGLPowerPreference',
    writeable: false,
  },
  WorkerType: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'WorkerType',
    writeable: false,
  },
  XMLHttpRequestResponseType: {
    isTypeVariable: true,
    isValueVariable: false,
    name: 'XMLHttpRequestResponseType',
    writeable: false,
  },
};
